### ISSUE TITLE
Introduce quotas for re-encryption nodes

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#11]
Introduce quotas for re-encryption nodes; the quotas are in accordance with the stake at the node address, stored in Ethereum blockchain

**Comment by michwill** [comment]
Quotas are checked by the amount of our ERC20 token held by the nodes. No need to check in a smart contract, just by checking balances in associated thereum wallets

**Comment by jMyles** [comment]
So, the quota won't be for actual re-encryption work done at the node in question, just that the node holds tokens from *someone* having done re-encryption (or having purchased them)?

**Comment by michwill** [comment]
The quota is for holding re-encryption keys and being available to do re-encryptions. So yes, not for the number of re-encryptions made

**Comment by tuxxy** [comment]
Won't fix.
