### ISSUE TITLE
ecdsa_gen_priv and ecdsa_priv2pub don't seem to prepend key bytes with metabyte 

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#125]
`api.ecdsa_gen_priv` gives back key bytes that don't contain the metabyte at the beginning to indicate what kind of key.

Currently, there's a failing test shown in #124 by dint of this issue.

**Comment by tuxxy** [comment]
Won't fix.

`pyUmbral` resolves this.
