### ISSUE TITLE
Sign kFrag data from Alice

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#13]
All kFrags that come from Alice will need to be Signed by her so that Ursula can check the validity of them.

**Comment by tuxxy** [comment]
Before this can be implemented, split-key re-encryption needs to be added so we know what we're signing first.

**Comment by michwill** [comment]
I think, when we're "emulating" split key with bbs98 as 1-of-n, the signing still works the same way with the full re-encryption key, so it doesn't depend on whether kFrag is kFrag or a full re-encryption key

**Comment by tuxxy** [comment]
Done.
