### ISSUE TITLE
Bob requests re-encryption: what URL?  what payload?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#132]
OK, team, so Bob is ready to request re-encryption.

He has the treasure map.

He uses it to find an Ursula.

What does he do?

Presumably, he POSTs to some URL, right?

1) What's the URL?
2) What's the payload?

**Comment by jMyles** [comment]
@michwill says: Bob comes up with policy ID (or several policy IDs for subpaths?) and requests Ursula to re-encrypt. And she does for whatever is there

So, basically this policy ID is either in the URL, or posted to some URL

**Comment by jMyles** [comment]
Right, but it is the same URL as the kFrag?  ie, `/kFrag/{hrac}'?

And then the payload - is it just cFrag in bytes?

**Comment by michwill** [comment]
Ah! Right, that should work imo

**Comment by tuxxy** [comment]
Could probably have a url at `/reencrypt/{hrac}/` and have the POST data contain the data required for reencryption.

**Comment by michwill** [comment]
That works also.
I think, this would work even better b/c we can avoid having any json fluff around the data and just stream the binary data stream to that url (so no need to worry about base64 encoding and such)

**Comment by jMyles** [comment]
I don't love that.  Why are we splitting the kfrag into a noun and a verb in the URL?  Is `reencrypt` a good url?

**Comment by tuxxy** [comment]
I don't understand?

We're telling the server to re-encrypt using the kfrag identified by `hrac` and then posting the data to re-encrypt there.

**Comment by michwill** [comment]
I see only an advantage of having to post binary data towards a url instead of something like
```
{
   'command': 'reencrypt',
   'payload': <some base64 stuff>
}
```

**Comment by jMyles** [comment]
But it's pretty unwieldy in terms of building out a REST API.  What's a "reencrypt"?  And why does it have the same `hrac` as a "kFrag"?  

When you POST to it, what are you making a new one of?

I am OK with it being a different URL, but to me, this kind of approach starts to conflate REST with RPC.

If we want a URL (so as not to need to parameterize the verb in JSON, as shown in @michwill's comment above), then I think that for proper REST, we need something like:

POST `/kFrag/{hrac}/work_orders` - this shows to all parties that the *new* object in the equation is an order telling Ursula to do some work.

**Comment by tuxxy** [comment]
That sounds way more overcomplicated than it needs to be compared to just POSTing data to an endpoint and letting the server take care of it. Tons of APIS do this.

**Comment by jMyles** [comment]
Overcomplicated?

How is `/noun/{id}/noun` more complicated than `/noun/{id}` / `/other_noun/{same_id}`

What good REST API does this?  I can't recall having seen one.  This is like REST 101, dude.

**Comment by tuxxy** [comment]
I don't understand what `work_orders` has to do with re-encryption?

**Comment by michwill** [comment]
If I understand correctly, @jMyles just proposes to have `/kFrag/{hrac}/create` for creating a policy, `/kFrag/{hrac}/reencrypt` for re-encryption and so on.
This sounds good to me

**Comment by tuxxy** [comment]
Ah, I see. Yeah, that's good.

**Comment by jMyles** [comment]
Not `create`, no - you just POST to `/kFrag/{hrac}`.

And then you POST to `/kFrag`/{hrac}/work_order` to create a new re-encryption work order, which of course Ursula is obliged to fulfill.

@tuxxy: As for what a "Work Order" has to do with re-encryption, be reminded of our discussion of this matter in @michwell's business center, which is documented here:

https://github.com/nucypher/nucypher-kms/wiki/Payment-Models:-The-Invoice

**Comment by michwill** [comment]
Yeah, my thinking was also that the "work order" initially will be just a request to re-encrypt initially. B/c proper payment by Bob requires microtransactions, which is not trivial (we'll see what spankchain dudes come up with wrt micropayments with erc20 tokens).

So, initially, I'd have Alice pre-paying the policy on blockchain w/o micropayments (and the info can go to /kFrag/{hrac), but Bob can post just data to /kFrag/{hrac}/something

**Comment by jMyles** [comment]
Right, exactly.  That's exactly my thought.

And I think it can still be a "work order," but Ursula can check to see if Alice has paid for this particular Bob in advance.  Or, as you point out, at first, will have required that Alice pre-pay and authorize this particular Bob.

I just think that a parallel universe of URLs with `/verb/{kFrag_id}` is much more confusing.  I'm not even sure what I'd expect OPTIONS to say for that.

**Comment by tuxxy** [comment]
I think I'd much rather prefer a verb there instead of `work_order`. It's not inherently RESTful, but many APIs do similar things because RESTful is so restrictive in this regard.

**Comment by tuxxy** [comment]
I would also add that I really don't think anyone is going to care if we follow RESTful standards 100% for our MVP just for the sake of following them. Chances are this will all be changed for different options in the future.

**Comment by jMyles** [comment]
Sure, I agree that nobody is likely to care, but I also think we don't need to set traps for ourselves.  

Having parallel URL schemas for the same set of discrete identifiers doesn't just fall short of being 100% RESTful, it's downright confusing.  

If you want it to be `/kFrag/{hrac}/reencrypt`, I guess that's OK, but it's certainly not as clear.  What state change is Bob taking responsibility for?  This URL sounds basically idempotent, like you're supposed to issue a GET to it, but obviously there's money involved, and that needs to be reflected.

**Comment by jMyles** [comment]
Bob isn't POSTing a "reencrypt", he's posting an explicit request for Ursula to perform re-encryption, with an understanding that she'll be paid for it.  By processing the request, Bob expects to take responsibility for creation of a new work order.  That's what he's POSTing.  

If "work order" is too vague, how about "reencryption_order", perhaps shortened to "reenc_order"?

**Comment by tuxxy** [comment]
`reenc_order` is much more clear to me than a `work_order`. Similarly, I don't expect every Jane Doe developer to have an intricate understanding of our protocol to use it and as such we should avoid using protocol level terms in the API URLs.

**Comment by jMyles** [comment]
Well that's exactly why I think "work order" is nice: it's not specific to our protocol.  Work orders are issued all over the place, in every industry, by many people of many levels of understanding.  

"Bob delivers a work order to Ursula" - I think basically everybody can glean from this that Bob is telling Ursula to do something for money.
