### ISSUE TITLE
pfrag class

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#137]
Currently, the only valid input for reencryption (ie, the second argument in `ecies_reencrypt`) is the encrypted key that comes out of `ecies_ephemeral_split_rekey` as its second argument.

This object (which @tuxxy names `eph_key_data` in `Alice.generate_rekey_frags`) is a tuple, where the first item is an instance of `npre.umbral.EncryptedKey` and the second is an instance of `nacl.utils.EncryptedMessage`.

We need a uniform way to de/serialize this so that Bob can send it over the wire to Ursula.

It also needs to be hashable so that it can be used in a mapping to track the result.

**Comment by michwill** [comment]
Indeed we do need that. I would much prefer the API to be consumed by @jMyles to be much higher level and work in the following manner:
```
ciphertext = api.encrypt(pub_a, <32-byte symmetric key or challenge pack, or whatever>)
sym_key = api.decrypt(priv_a, ciphertext)
rekeys = api.split_rekey(priv_a, pub_b)
cfrag = api.reencrypt(pfrag)
ct = api.combine(ciphertexts)
sym_key = api.decrypt(pub_b, ct)
```
All the variables (ciphertext, each of rekeys, pfrag, cfrag, ct) should either be bytes or have `__bytes__`. Importantly, the user of the API doesn't have to think about any ephemeral keys whatsoever

**Comment by jMyles** [comment]
Good grief, this is amazing.  Thanks for synthesizing the thoughts I was too hungry to properly lay out, @michwill.  :-)

**Comment by jMyles** [comment]
The one thing I'll add in terms of flavor:

I like (and, last we checked in, @tuxxy liked) having a discrete layer of the API that works only with bytes and is essentiall typeless.  

I had envisioned that rule being in force in something like `internal`, while `api` welcomed the use of some of the higher-level constructs.

It's also fine (and I think @tuxxy's preference) for `api` to work only with bytes and to have a different, higher-named layer that does the things you've outlined above.

**Comment by jMyles** [comment]
Also, I'll make the following critique:

instead of `cfrag = api.reencrypt(pfrag)`, I'd like `cfrag = api.reencrypt(kfrag, pfrag)`

**Comment by michwill** [comment]
Yes, indeed!

**Comment by tuxxy** [comment]
This is pretty much handled with the non-interactive Umbral, right
@michwill?

If so, do we want to just handle it here or should we refactor everything
now for it? I haven't scoped out what needs to change, but I will when I
get time. Until then, I can't say for certain how much work it will take.

**Comment by michwill** [comment]
It should be handled like this _somewhere_.
Non-interactive Umbral - you mean, the code in the branch created by David? Yes, although I didn't look carefully at it wrt how much refactoring is needed.

**Comment by tuxxy** [comment]
I was looking at it, I don't think much is needed wrt the actual Umbral
library. The refactoring will be heavy on our backend, however.

**Comment by michwill** [comment]
Yes. So in this thread I proposed how the API should interact with proxy re-encryption. Does it sound reasonable to you?

**Comment by tuxxy** [comment]
It sounds reasonable, yes. I'm just not sure how heavy the refactoring will
be to make this possible, though.

**Comment by michwill** [comment]
But I am guessing, that's how it should work. Otherwise it will be complex to digest for a developer, and also hard to integrate with other proxy re-encryption algorithms (which might not have ephemeral keys at all)

**Comment by michwill** [comment]
In a way, how I intended the API to be is how encrypting_keypair (which is still there but unused) is made (apart from serialization part)

**Comment by tuxxy** [comment]
Yes, you're right. I've tried to hide it as well as I could within the
current library and its still complex. I think non interactive is best.

**Comment by jMyles** [comment]
I think I want:
`from nkms.crypto.frags import KFrag, CFrag, PFrag`

...and for them all to implement `_EXPECTED_LENGTH`

**Comment by tuxxy** [comment]
We'll see. It depends how much refactoring is required that could
potentially make the refactoring a bit more intense. I'll see how that fits
in there.

**Comment by michwill** [comment]
At the end of the day, it's software, "can be written over the weekend" (c) Bill Gates :joy:

**Comment by tuxxy** [comment]
Haha indeed
