### ISSUE TITLE
Bob can generate work orders based on his TreasureMap, he doesn't need a PolicyGroup.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#140]
Currently, Bob has a method with the following signature:

`def generate_work_orders(self, policy_group, *pfrags, num_ursulas=None):`

But this is repeating data, because Bob can reconstruct the `policy_group` from his `TreasureMap` - in fact it's unlikely in the real world that he'll have reconstituted it any other way.

**Comment by michwill** [comment]
Indeed!
