### ISSUE TITLE
Implement Ursula's delivery of a (real or fake) ChallengePack for the beta?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#146]
Do we want Ursula to store and deliver something that *can be* a `ChallengePack` for the beta?

If we decide that the answer is 'no,' then we'll need to get all Ursulas to upgrade in order to be compatible with the challenge protocol.  If we decide "yes," then we can just fake the data for now and then implement it later without Ursula needing to change anything.

**Comment by jMyles** [comment]
A big part of this comes down to whether we are ever even going to implement the challenge protocol.  If there's a way to validate re-encryption correctness without divulging the `KFrag`, we may not need it.

**Comment by jMyles** [comment]
Per our conversation on the phone today, I'm consider this a "no."  I'll finish ripping the relevant parts out, and we can start implementing #147 instead.

**Comment by tuxxy** [comment]
Won't fix.
