### ISSUE TITLE
How does Bob learn the value of m?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#150]
`Bob` is able to learn the value of `n` (the total number of fragments of a `Policy`) by obtaining a `TreasureMap` and measuring its `len`.

However, we haven't yet devised a place for `Alice` to inform `Bob` of the value of `m` (the minimum mass of cFrags required to glean The Secret).  

How shall we instruct `Bob` to find m?

**Comment by michwill** [comment]
I think, same way. Configuration file + override in user app?

**Comment by tuxxy** [comment]
Done, it's in the `TreasureMap`.
