### ISSUE TITLE
Do the tests currently cover a scenario in which the re-encryption recipient's secret key is not needed?

### ISSUE THREAD

**Issue by ckaye89** [nucypher/nucypher-kms#17]
Looking at this [blog post](https://hackernoon.com/proxy-re-encryption-playground-in-python-3bc66170b9bf):

> But there’s a way to do it with the current algorithm. When Alice delegates access to Bob, she can generate an ephemeral key `sk_e` and produce a re-encryption key `rk_ae`. Then she encrypts `sk_e` with Bob’s public key `pk_b` yielding `e_b`.

> The proxy will be given both `rk_ae` and `e_b`. When Bob connects, the proxy will hand him `e_b`. Then Bob can extract `sk_e` out of it and use that to decrypt encrypted messages coming from the proxy.

Am I right in thinking that this portion of the story is not yet tested in `tests.test_default_crypto`?

**Comment by michwill** [comment]
Eh, good point. Actually, that's exactly the situation which is implemented and tested.

However, I forgot to remove sk_b (which was for debug purposes) from the method. Removed it now
