### ISSUE TITLE
Config.  Config Config Config.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#176]
Where are we on config?

#119 is pretty much stale, right?  It's time to get config going.

**Comment by tuxxy** [comment]
Yes, it's stale and old.

I've closed the PR, we should scope a new one now.

**Comment by jMyles** [comment]
I'll offer some wandering thoughts:

1) To my way of thinking, the most important rule to follow when doing config in python is "don't be like Django."  The following few points will offer ways to be not like Django.
2) Ensure that config can be injected everywhere its needed.  Never realize config in a global way, nor prevent a caller from overriding config if they choose to do that.
3) Once config is set for a given runtime, make its references immutable (although it's OK to mutate the objects therein referred) and thread-safe.
4) Make file-representations of config (in our case, something like config.yaml) complete deterministic precursors to the in-memory objects.

Some loosing thinking about the how and the what:

5) Jeez I like curses.  I can imagine a nice streamlined curses interface which spits out a properly formatted config file (along with generated keys).
6) Config files need to be easy to read, with no options that do nothing.  Let's keep it to under 20 configurable options.
7) Let's make Config reasonable safe - whether or not we like it, people will clone-and-modify config.  Let's have nice sanity checking around things.
8) I like the idea of shipping "example apps" with Configs provided.

That's... all for now.  I'm not wedded to anything I've said here - like I say, just some wandering thoughts.

**Comment by tuxxy** [comment]
We have made major movement on this and I think we can close this issue. What say you @jMyles?
