### ISSUE TITLE
Enrique: the forgotten hero of PRE

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#182]
I have been increasingly bothered lately by a nagging thought that our cryptology has given short-shrift to a Character whose power in the context of the PRE narrative is potentially incredible.

Until now, all of our logic assumes that Alice does two things:

1) Generates KFrags and puts in motion the mechanics of a `Policy`
2) Encrypts The Secret for Bob, leaving a `Capsule` for him to find.

...but why do we presume that these two things are done by the same person?

Now, of course, in an orthodox PKE cryptological narrative, Alice is chiefly identified by her performance of the latter function - she is the one with the message for Bob.

On that basis, it may be tempting to continue to tie her to this idea, carving out the former and naming a different Character.  But, as @tuxxy pointed out to me in the pool just a little while ago, this actually doesn't make sense: the consequence of Alice's presence on the network follows her private key (ie, that's what makes her who she is, and reminds us of the attack surfaces which we must defend on her behalf).  And it is the "delegator" who needs a private key, not the "encapsulator."

So, on that basis, I propose that we begin a tradition of regarding the PRE narrative as involving *four* actors by introducing **Enrique the Encapsulator** (or, if we're feeling cheeky, "the pharmacist" - ie, he makes `Capsules`).

This opens up the ability to reason about a number of compelling use-cases, such as the following:

A user wants to build a distributed feed of operations data for a swarm of nodes (NuCypher or otherwise).  This user wants to delegate in advance who may consume such a feed, but wants to disappear from the network afterward, leaving the authority structure in place.  Here's how that works:

* Alice meets and selects 12 Bobs who are authorized to consume the data feeds.
* She `grants` access to each of those 12 Bobs, and then deletes her private key (or perhaps keeps it on a hardware wallet or similar).  Let's refer to this scenario as "DisappearingAlice".
* Each app which wants to publish data for the 12 Bobs encrypts for Alice's public key.
* Each Bob embarks on The Quest per usual.

Of course it is step 3 here that is typically absent from our use case discussions, but notice the turn of events here: Now, *anybody* can encrypt for all 12 Bobs, simply by knowing Alice's public key. 

My sense - and this is just preliminary, based on a few days of deep thoughts about it - is that all of the most mind-blowing uses cases for NuCypher will be of the four character narrative.

I also propose that if indeed Alice is also Enrique, we call her BigAlice.  

Among the consequences of this change for the codebase:

* We create a `DelegatingPower` which is part of the `grant` flow; with it, a user can perform `generate_kfrags(...)`.
* We establish `Enrique` and move `encrypt()` there.
* We establish the necessary facilities for DisappearingAlice.

**Comment by cygnusv** [comment]
This is something we have been discussing indirectly and it is good to come up with a way to support it explicitly in the KMS. The main advantage of PRE with respect to other approaches appears when you consider that a single delegation action from Alice (i.e., a Policy) enables multiple data producers (i.e., Enriques), multiple data consumers (i.e., Bobs), and multiple pieces of data (i.e., Capsules). 

Here's a diagram that more or less summarizes this situation, in case it makes things clearer.
![domains-pre-cloud](https://user-images.githubusercontent.com/2564234/38001211-7b16a284-31e0-11e8-84b2-301e183fd0a9.png)

**Comment by michwill** [comment]
Physically though, it's still multiple re-encryption keys. Perhaps, it makes sense to keep calling it multiple (per Bob) policies.
We could bunch multiple policies in one request if we wanted to, of course. But I think we want the flexibility of revocation of an individual Bob

**Comment by cygnusv** [comment]
Yeah, that's true. Then, I should rephrase that to this:

> A single delegation action from Alice (i.e., a Policy) enables access by a single consumer (i.e., Bob), but for multiple pieces of data (i.e., Capsules), and multiple data producers (i.e., Enriques).
