### ISSUE TITLE
Ensure that `set()` method of DHT implementation does not use same node as storage

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#19]
Quoting architecture.rst:

> Kademlia by default (see kademlia.network.server) saves data in multiple nodes, and also clients are servers there.

> We need to split up client and server (that is, get and set methods of the client don't save data in the current node).

Currently, `set` calls `set_digest` which in turn calls `self.protocol.router.findNeighbors` on the `Node` instance.

**Comment by michwill** [comment]
Right. We need to find n currently online neighbors which don't have the quota exhausted (can leave the quota not implemented for now though). And give individual rekeys to each of the n neighbors corresponding to the same rekey id (which is calculated from the pubkey and path corresponding to this rekey).

So, in a way, you call save_rekeys with n rekeys. And you cannot read the rekeys from there, only remove

**Comment by jMyles** [comment]
This appears to be non-trivial.

Currently, a `Server` needs to have a `protocol` in order to run its `set` method.  This is the only way it can determine if a node is able to receive a datagram.  

However, the protocol is instantiated by dint of `create_datagram_endpoint` having been called.  Teasing this out will require at least medium surgery on all at least the Server and Protocol classes.  

Per our conversation on Slack, it's not clear to me whether this is worth the engineering effort.  

I'll do a bit more examination.

**Comment by michwill** [comment]
Yes, the surgery will certainly be required. Or you think that the surgery is so serious that we're re-implementing everything?)

**Comment by jMyles** [comment]
Closed by 8f50953.
