### ISSUE TITLE
Modify kademlia.protocol.KademliaProtocol

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#2]
The protocol specified in Modify kademlia.protocol.KademliaProtocol should be subclassed or re-written to re-encrypt data instead of just storing it. It should provide methods:
- store_rekey
- remove_rekey
- reencrypt

**Comment by jMyles** [comment]
I'll close this - we have a custom `Protocol` class, even though our idea of what the `Protocol` needs to do has changed since this ticket was authored.
