### ISSUE TITLE
Ensure that Alice pays for cancelled arrangement period

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#214]
<a href="https://github.com/tuxxy"><img src="https://avatars1.githubusercontent.com/u/3598318?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tuxxy](https://github.com/tuxxy)**
_Wednesday Apr 04, 2018 at 22:00 GMT_
_Originally opened as https://github.com/nucypher/nucypher-kms-ethereum/issues/18_

----

Let's say Alice creates an arrangement for 20 Ursulas.

Alice decides she doesn't like a particular Ursula storing a KFrag _the same period that she publishes an arrangement_ and wants to specifically revoke that KFrag.

We should ensure that Alice pays for the period that she revokes on. If she revokes on day 0 of the arrangement, she should pay for day 0.

**Comment by jMyles** [comment]
<a href="https://github.com/michwill"><img src="https://avatars0.githubusercontent.com/u/740600?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michwill](https://github.com/michwill)**
_Thursday Apr 05, 2018 at 20:22 GMT_

----

I think, this is how it works. Although, I'd let @szotov to confirm that

**Comment by jMyles** [comment]
<a href="https://github.com/szotov"><img src="https://avatars3.githubusercontent.com/u/22225795?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [szotov](https://github.com/szotov)**
_Thursday Apr 05, 2018 at 20:29 GMT_

----

Alice can revoke fee only for next periods. Payment for first/current period (0 day) will be irrevocable.

**Comment by jMyles** [comment]
<a href="https://github.com/michwill"><img src="https://avatars0.githubusercontent.com/u/740600?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michwill](https://github.com/michwill)**
_Thursday Apr 05, 2018 at 20:38 GMT_

----

So, she gets refunded only for future periods?
Sounds good to me

**Comment by michwill** [comment]
Looks like this is how it's currently works, so can be closed. Correct, @szotov ?

**Comment by szotov** [comment]
Right
