### ISSUE TITLE
Time Limited Policies

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#3]
The simplest policy for rekeys is time limit. Nodes should have a configuration of how long they promise to store re-encryption policies for. This probably can be later written on blockchain so that clients and validators can be always aware of it

**Comment by jMyles** [comment]
1. Ursula is permitted to remove any payloads for policies which are expired.
2. Ursula will not be paid for re-encryptions pursuant to an expired policy.

**Comment by tuxxy** [comment]
@jMyles Please update this with more specific/relevant details. :)

**Comment by jMyles** [comment]
We have indeed decided on this.  Closing.
