### ISSUE TITLE
Designing Ethereum smart contract for oracles

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher-kms#32]
Oracles will determine who needs to pay who (based on which Ursulas are misbehaving, etc). Each of them has a table of who needs to pay who and how much.

After that, oracles bet on the correct result, and the smart contract determines the Truth by the stake-majority vote.

This method can have its own problems, so it could be changed!

**Comment by michwill** [comment]
We need to make the voting anonymous until the result is revealed.
The threat here: if everyone can observe votes of others, everyone can just blindly follow the first voter.

The solution: the well-established problem of anonymous voting. Rather than electing presidents though, the vote determines what's the correct money-moving order (or even hash!) to execute.

Paper: http://digital-library.theiet.org/content/journals/10.1049/iet-ifs.2008.0127
Implementation for Ethereum: https://github.com/stonecoldpat/anonymousvoting

**Comment by michwill** [comment]
The trick with this protocol is that it only can vote "no" or "yes". But if we have a hash of the bill "who pays who", the oracles can vote on what each bit of the bill should be.

Of course, how expensive is it (for oracles) in terms of gas is a good question...

**Comment by michwill** [comment]
At current prices, looks like the naive implementation (bit-wise voting) will be $4/vote/bit for every voter, for 40 voters (sic! that's a lot). The good news is that it scales well (e.g. the price per voter remains approx. constant when the number of voters increases)

**Comment by michwill** [comment]
Another paper which is probably towards the same direction http://arxiv.org/abs/1708.01171

Perhaps, I need to contact one of the authors of both papers (Patrick McCorry, for example) to figure out whether the new changes in Ethereum make it cheaper / how to do it cheaper in our case

**Comment by michwill** [comment]
Corresponding wiki entry: https://github.com/nucypher/nucypher-kms/wiki/Ursula-consensus-through-betting-on-the-result-of-voting

**Comment by michwill** [comment]
Possibly, we'll be able to do ECMUL for 40k gas (~$0.04) if we use alt_bn128 elliptic curve in the new ethereum release [https://github.com/ethereum/EIPs/pull/213]

**Comment by michwill** [comment]
Well, ok, looks like the vote contains 8 elliptic curve multiplications, so it would take 320k gas (more like 350k with everything else). This would lead to recommended tx fee of $0.4, and if it's 5 cents - it would be 10 minutes confirmation. So looks affordable enough. If I figure out a good way to avoid calculating the vote for every single bit!

**Comment by michwill** [comment]
Oh wow, actually since we don't want to keep in secret who voted for which variant at the time of calculating the tally, the protocol can be way easier and faster. For example:
```
for oracle in oracles:
    with oracle:
        publish(sha3(nonce + vote), sha3(nonce))
for oracle in oracles:
    with oracle:
        publish(nonce, vote)
    verify(sha3(nonce + vote) is correct)
    verify(sha3(nonce) is correct)
# whoever will be not in time to prove their vote is out
total_vote = sum(correct votes)
```
Hashes are super-cheap, and no elliptic curve crypto needs to be involved, neither we need fancy zero knowledge proofs. And here we actually *want* to know what are the votes. Oracles just commit to not change the vote in future, and then everyone reveals their vote.

**Comment by jMyles** [comment]
After some discussion about this concept at the 1kx retreat, it seems that these are called "Trustless Quorums."  Since we are planning to launch to testnet without one, I'll close this issue and we can open subsequent issues on the KMS-eth codebase for specific implementation stuff.
