### ISSUE TITLE
`Client.encrypt_key` method doesn't return a list of one key if no path is specified

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher-kms#33]
When calling `Client.encrypt_key` with a `path` equivalent to `None`, the key is returned without being encapsulated by a `list`.

This method should always return a key encapsulated by a `list` object, even if there is only one key to return. Doing so will help standardize the Cryptographic API more.

This isn't explicitly required for now, so I'm putting it on the backburner since it will be sorta annoying to refactor the tests for this.

**Comment by jMyles** [comment]
> This method should always return a key encapsulated by a list object, even if there is only one key to return. Doing so will help standardize the Cryptographic API more.

Did you perhaps mean to always include the case where there is *no* key to return?

**Comment by tuxxy** [comment]
Ah, didn't see this til now..

`Client.encrypt_key` should always return an encrypted key when called, if it doesn't that would be a fail state.

**Comment by tuxxy** [comment]
This method has been deprecated in its current form.
