### ISSUE TITLE
Proper hash functions for signatures and content

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#45]
Per @tuxxy, we'll use keccak-256 for signatures and sha3-256 for content.

**Comment by tuxxy** [comment]
We can actually use Keccak-256 for both. It might be more favorable.

**Comment by jMyles** [comment]
When you say, "it might be" - what exactly are the stakes?

How will we make the decision?

For now, I'll keep it as two wrapper functions that both use keccak-256.

**Comment by tuxxy** [comment]
There are no stakes, just that it becomes more compatible with the Ethereum Blockchain and smart contracts if it needs to for any future reason.
