### ISSUE TITLE
Logic to generate re-encryption keys.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#47]
See: https://github.com/nucypher/nucypher-kms/pull/44/files#diff-1ef8ad9f0872558034a3d37e11f8b81dR2

**Comment by tuxxy** [comment]
Are we waiting on the split-key stuff for this, or should I add this to my TODO?

**Comment by michwill** [comment]
Split-key first. It actually already works, need to talk to David again about the best way to refactor it

**Comment by tuxxy** [comment]
Rather than use a `keygen` module, we can go ahead and implement this on the `KeyRing`.

**Comment by michwill** [comment]
Yes, kFrags - that's what I meant

**Comment by tuxxy** [comment]
Implemented in #55.
