### ISSUE TITLE
Logic to update treasure map

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#48]
Currently, `Policy.treasure_map` is just a list, and `Policy.update_treasure_map()` appends to that list.  We need logic that allows it to actually interpret a policy offer result and update itself.

**Comment by michwill** [comment]
Let's start with the logic which fills it up with mock data, and replace with actual kFrags then. Or, by that time we may have the working PRE in a proper form

**Comment by jMyles** [comment]
We already the fake data implementation; that's in my pr.

**Comment by michwill** [comment]
Ah, great

**Comment by tuxxy** [comment]
Done.
