### ISSUE TITLE
Network protocol handshake / upgrade for Ursula - Alice

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#61]
Ursula can be discovered by all other actors via a DHT via UDP (kademlia uses rcpudp for this purpose).

However, once this discovery has occurred, a handshake ensues which enabled an upgraded communications paradigm.  The exact nature of this upgrade varies depending on the actor.  

This Issue concerns the ability for Alice, having discovered Ursula, to craft and offer a Policy.

**Comment by tuxxy** [comment]
Done.
