### ISSUE TITLE
What does TreasureMap include?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#64]
A TreasureMap is valid for an entire `PolicyGroup`.  The TreasureMap is encrypted for Bob and signed by Alice.

Obviously, at a minimum, it includes the node IDs for all Ursulas to whom Alice bestowed a kFrag.

But what else?  Some possibilities:

* The public key which each Ursula presented.
* A fingerprint of The Stake which Ursula held at the time.

Maybe we only need the former.  But this will establish that Ursula is the same person (or at least, is holding the same Stake) as the person to whom Alice gave the kFrag.

**Comment by michwill** [comment]
I think the former (public key of each Ursula) is fine indeed. Idk what the second part (historical stake amount) would give you
