### ISSUE TITLE
KeyRing.add_key() / .add_keypair

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#69]
We're transforming `KeyRing` into a class that more literally applies the metaphor of a `KeyRing`, and also borrows from `KeyRing` concepts from other cryptographic practices, such as PGP.

The touchstone methods for this functionality will be something like `.add_key()` and `.add_keypair()`.

The API... is still coming together.

One possibility is `.add_key(bob_pubkey_sig)` - if a single argument is given, it establishes a new character on the KeyRing - in this case Bob.  Characters are represented as a string, in the form `{character_name}_{pubkey_sig_fingerprint}`.  

`.add_key(bob_pubkey_sig, pubkey_encrypt=key)` adds Bob's encryption key, so that `KeyRing` can encrypt for him.

**Comment by tuxxy** [comment]
Implemented in #84
