### ISSUE TITLE
KeyRing.encrypt_for

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#70]
The `KeyRing` method to encrypt text for another person using that person's public encryption key.

`keyring.encrypt_for("bob_e24f005b", plaintext, sign=True)`

`encrypt_for()` returns a tuple, where the first element is the ciphertext, and the second element is either the signature or the `NO_SIGNATURE` constant.

**Comment by tuxxy** [comment]
Do we have a solution for storing these keys yet? If not, it's gonna make it a bit more complex to get a solution like this working unless we have something like lmdb or redis up to access and import the keys from.

**Comment by michwill** [comment]
You can use our lmdb: https://github.com/nucypher/nucypher-kms/blob/master/tests/test_db.py

**Comment by jMyles** [comment]
Closing as no-longer relevant.

The `encrypt_for()` method now lives on `Character` and implements its lower-level equivalent on `CryptoPower`.
