### ISSUE TITLE
KeyStore.KeyNotFound

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#71]
`KeyNotFound` is an exception raised by a `KeyStore` when the user tries to access or use a key that the `KeyStore` doesn't have.

For example, calling `keystore.get_key("key_fingerprint")` will result in a `KeyNotFound` error if the `key_fingerprint` doesn't exist to the `KeyStore`.

**Comment by jMyles** [comment]
Obviously, with the transition to `KeyStore`, this is a little different now.  I think we just want `KeyNotFound` (a subclass of `KeyError`) whenever we ask `KeyStore` for a key we haven't yet stored.  Right?

**Comment by tuxxy** [comment]
Yeah, that sounds like what I was thinking of. Side question: is there any benefit to it being a subclass of `KeyError` instead of a regular `Exception`?

**Comment by jMyles** [comment]
Yeah, I think so - higher-level APIs can then except around various `KeyErrors`.  Generally, unless you have a truly novel logical exception, I think it's good to subclass an existing subclass of `Exception`.

**Comment by tuxxy** [comment]
Will do. Updating the issue info now.

**Comment by tuxxy** [comment]
Implemented in #87
