### ISSUE TITLE
Encrypt KeyStore private keys

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher-kms#88]
In an earlier issue, the idea was raised to encrypt the private keys in the `KeyStore` with a key from:

* The config file
* A user password
* From Nucypher KMS itself

We should look into implementing one of these when we feel it is needed, or users request such an option.

**Comment by jMyles** [comment]
@tuxxy: We've more-or-less decided to not even store private keys in the KeyStore any more, right?  Can we close this?
