### ISSUE TITLE
Some network tests leave dirty state

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms#90]
Some of the network tests, such as `test_treasure_map_from_alice_to_ursula` leave network resources in a dirty state which may cause subsequent tests to unfairly pass.

It's probably best to manually wipe every Ursula between tests; some other measures may be necessary as well.

**Comment by jMyles** [comment]
I mean, look, maybe we just tell them that, if they want to sell such devices to people, they have to include a copy of their codebase to that person.  They can still ask the user to sign a ToS saying they won't further distribute it.

At the end of the day, that's the point, right?  If you're going to build a medical device using our KMS, you need to tell your user *exactly* what you're doing.  I can get behind that, but I just want to be clear about the implications.

**Comment by michwill** [comment]
What do you mean by "dirty state"? Some unexpected Ursula serving?

**Comment by jMyles** [comment]
Indeed.  However, now, with the fixture format, I think this is no longer an issue.  I'm comfortable closing.
